on: 
  push:
    branches:
      - staging
# name: 🚀 Deploy website on push
name: FTP-Deploy-Action
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        # server: diybuilder.in
        # username: ${{ secrets.FTP_USERNAME }}
        # password: ${{ secrets.FTP_PASSWORD }}
        # server-dir: /public_html/staging.watch.com/        
        ftp-server: ${{ secrets.FTP_SERVER }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: toupload